### PR TITLE
Added Build script to setup the environment for running code.

### PR DESCRIPTION
**Pull request by PrajitP**
Added environment setup documentation in README file.

Note: In the code I see a lib path pointing to local directory, we can remove that code. I have not ran any tests, we will also have to add test modules dependencies in 'Build.PL'.

I like the idea of Language server and unfortunately there is none for Perl, I would like to contribute to this project.

### CODE REVIEW

**Comment by cazador481** [comment]
Thank you for your contribution.  The project doesn't need a build.pl file, as it is a dzil based project.  
The project uses dzil.  To generate a release package you can do.  dzil build
to install you just need to do dzil install.  

I'll go ahead and update the README file with those instructions.

**Comment by PrajitP** [comment]
Hi Eddie,

Thanks for pointing that out, I will try to build it with your updated
instruction,
next I am going to try to connect this with neovim and understand the
codebase.

If you have already tried connecting to neovim, I would love to get some
documentation about it.

Thanks,
Prajit

**Comment by cazador481** [comment]
I added instructions on the wiki on how to connect to neovim.  https://github.com/cazador481/App-LanguageServer-Perl/wiki/Use-in-neovim

**Comment by PrajitP** [comment]
Hi Eddie,

Thanks for sharing the wiki,
I was able to finally install and use this with neovim (Now I have a good
starting point),
I have few suggestion for Readme & wiki.

1) In README.md

Installation instructions
> This project is based on dzil. To install the develoment version you need
> to run
>
>    - cpanm Dist::Zilla
>
>
>    - dzil listdepedencies | cpanm
>
>
>    - dzil install
>
> a)  The highlighted red section seems to be wrong command, I was finally
able to install dependencies using

dzil authordeps --missing | sudo cpanm

b) I found one of dependency missing from the list which I had to install
manually

Pod::Elemental::Transformer::List

c) I am guessing (by looking at neovim usage wiki) that running of
command *dzil
install* will add this project bin path to $PATH variable, is it correct?
(Didn't happen for me though)

2) In Wiki

let g:LanguageClient_serverCommands = {
  \ 'perl': ['slp.bin'],
  \ }" AutoStart Language Serverlet
g:LanguageClient_autoStart=1autogroup FileType perl  " Smart Variable
renaming
  nnoremap <silent> <F2> :call
LanguageClient_textDocument_rename()<CR>  "gq will now use the format
your code properly.
  set formatexpr=LanguageClient_textDocument_rangeFormatting()  "
remaps = to gq, since equal program doesn't allow using a function
  nnoremap = gqendgroup END

a) The highlighted pink section should point to executable, 'bin/spl.pl' in
project directory, Assuming in above comment 1-c added the project bin path
to $PATH,
it can not find executable 'spl.pl' (not spl*.bin*), anyway I don't see a
path added top $PATH, so I had to mention full path there.

b) Neovim complains not an editor command for 'autogroup' and 'endgroup'

*Fun fact*: I use to work at NVIDIA India(Testgen Team) and I probably have
seen your name at few places. Its great to work with someone form NVIDIA
again :)

Thanks,
Prajit

**Pull request closed without merging**
